//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontMaker.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontMaker.Resources.Lang.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加数字 的本地化字符串。
        /// </summary>
        public static string AddDigits {
            get {
                return ResourceManager.GetString("AddDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加数字 0-9 的本地化字符串。
        /// </summary>
        public static string AddDigitsTooltip {
            get {
                return ResourceManager.GetString("AddDigitsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加小写字母 的本地化字符串。
        /// </summary>
        public static string AddLowercase {
            get {
                return ResourceManager.GetString("AddLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加小写字母 a-z 的本地化字符串。
        /// </summary>
        public static string AddLowercaseTooltip {
            get {
                return ResourceManager.GetString("AddLowercaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加标点符号 的本地化字符串。
        /// </summary>
        public static string AddPunctuation {
            get {
                return ResourceManager.GetString("AddPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加常用标点符号 的本地化字符串。
        /// </summary>
        public static string AddPunctuationTooltip {
            get {
                return ResourceManager.GetString("AddPunctuationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加大写字母 的本地化字符串。
        /// </summary>
        public static string AddUppercase {
            get {
                return ResourceManager.GetString("AddUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加大写字母 A-Z 的本地化字符串。
        /// </summary>
        public static string AddUppercaseTooltip {
            get {
                return ResourceManager.GetString("AddUppercaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string AdvanceSetting {
            get {
                return ResourceManager.GetString("AdvanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点阵字库生成器 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arduino文件 (*.ino)|*.ino 的本地化字符串。
        /// </summary>
        public static string ArduinoFileFilter {
            get {
                return ResourceManager.GetString("ArduinoFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点阵数据起始位置 的本地化字符串。
        /// </summary>
        public static string BitmapDataStartPosition {
            get {
                return ResourceManager.GetString("BitmapDataStartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位序 的本地化字符串。
        /// </summary>
        public static string BitOrder {
            get {
                return ResourceManager.GetString("BitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位序排列 的本地化字符串。
        /// </summary>
        public static string BitOrderLabel {
            get {
                return ResourceManager.GetString("BitOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从左到右 的本地化字符串。
        /// </summary>
        public static string BitOrderLeftToRight {
            get {
                return ResourceManager.GetString("BitOrderLeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从右到左 的本地化字符串。
        /// </summary>
        public static string BitOrderRightToLeft {
            get {
                return ResourceManager.GetString("BitOrderRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节宽度 的本地化字符串。
        /// </summary>
        public static string ByteWidthLabel {
            get {
                return ResourceManager.GetString("ByteWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析字体路径: {0} 的本地化字符串。
        /// </summary>
        public static string CannotParseFontPath {
            get {
                return ResourceManager.GetString("CannotParseFontPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画布 的本地化字符串。
        /// </summary>
        public static string CanvasSize {
            get {
                return ResourceManager.GetString("CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符： 的本地化字符串。
        /// </summary>
        public static string Char {
            get {
                return ResourceManager.GetString("Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个字符数据格式 的本地化字符串。
        /// </summary>
        public static string CharacterDataFormat {
            get {
                return ResourceManager.GetString("CharacterDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符索引超出范围: {0} 的本地化字符串。
        /// </summary>
        public static string CharacterIndexOutOfRange {
            get {
                return ResourceManager.GetString("CharacterIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符输入 的本地化字符串。
        /// </summary>
        public static string CharacterInput {
            get {
                return ResourceManager.GetString("CharacterInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以直接输入或粘贴字符，支持多行文本 的本地化字符串。
        /// </summary>
        public static string CharacterInputHint {
            get {
                return ResourceManager.GetString("CharacterInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已清空字符 的本地化字符串。
        /// </summary>
        public static string CharactersCleared {
            get {
                return ResourceManager.GetString("CharactersCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已排序字符 的本地化字符串。
        /// </summary>
        public static string CharactersSorted {
            get {
                return ResourceManager.GetString("CharactersSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符数：0 的本地化字符串。
        /// </summary>
        public static string CharCount {
            get {
                return ResourceManager.GetString("CharCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符数：{0} 的本地化字符串。
        /// </summary>
        public static string CharCountFormat {
            get {
                return ResourceManager.GetString("CharCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 的本地化字符串。
        /// </summary>
        public static string CharNotFound {
            get {
                return ResourceManager.GetString("CharNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集 的本地化字符串。
        /// </summary>
        public static string CharSet {
            get {
                return ResourceManager.GetString("CharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集编辑器 的本地化字符串。
        /// </summary>
        public static string CharsetEditorTitle {
            get {
                return ResourceManager.GetString("CharsetEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集不能为空，请至少输入一个字符 的本地化字符串。
        /// </summary>
        public static string CharsetEmptyMessage {
            get {
                return ResourceManager.GetString("CharsetEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集文件 (*.cst)|*.cst|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string CharSetFilter {
            get {
                return ResourceManager.GetString("CharSetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集管理器不能为空 的本地化字符串。
        /// </summary>
        public static string CharsetManagerCannotBeNull {
            get {
                return ResourceManager.GetString("CharsetManagerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集名称 的本地化字符串。
        /// </summary>
        public static string CharsetName {
            get {
                return ResourceManager.GetString("CharsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入字符集名称 的本地化字符串。
        /// </summary>
        public static string CharsetNameEmptyMessage {
            get {
                return ResourceManager.GetString("CharsetNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入字符集名称 的本地化字符串。
        /// </summary>
        public static string CharsetNamePlaceholder {
            get {
                return ResourceManager.GetString("CharsetNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符预览 的本地化字符串。
        /// </summary>
        public static string charView {
            get {
                return ResourceManager.GetString("charView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C头文件 (*.h)|*.h 的本地化字符串。
        /// </summary>
        public static string CHeaderFileFilter {
            get {
                return ResourceManager.GetString("CHeaderFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查字符是否存在 的本地化字符串。
        /// </summary>
        public static string CheckCharExists {
            get {
                return ResourceManager.GetString("CheckCharExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string ChineseSimplified {
            get {
                return ResourceManager.GetString("ChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清空所有字符吗？ 的本地化字符串。
        /// </summary>
        public static string ClearAllConfirmMessage {
            get {
                return ResourceManager.GetString("ClearAllConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认清空 的本地化字符串。
        /// </summary>
        public static string ClearAllConfirmTitle {
            get {
                return ResourceManager.GetString("ClearAllConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空所有字符 的本地化字符串。
        /// </summary>
        public static string ClearAllTooltip {
            get {
                return ResourceManager.GetString("ClearAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载配置文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigLoadFail {
            get {
                return ResourceManager.GetString("ConfigLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigSaveFail {
            get {
                return ResourceManager.GetString("ConfigSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前： 的本地化字符串。
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前字符 的本地化字符串。
        /// </summary>
        public static string CurrentChar {
            get {
                return ResourceManager.GetString("CurrentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义字符集 的本地化字符串。
        /// </summary>
        public static string CustomCharSet {
            get {
                return ResourceManager.GetString("CustomCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}字节宽度] + [{0}字节高度] + [点阵数据] 的本地化字符串。
        /// </summary>
        public static string DataCompositionBreakdown {
            get {
                return ResourceManager.GetString("DataCompositionBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格式说明: 的本地化字符串。
        /// </summary>
        public static string DataFormatDescription {
            get {
                return ResourceManager.GetString("DataFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认位深度 的本地化字符串。
        /// </summary>
        public static string DefaultBitDepth {
            get {
                return ResourceManager.GetString("DefaultBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认导出目录 的本地化字符串。
        /// </summary>
        public static string DefaultExportDirectory {
            get {
                return ResourceManager.GetString("DefaultExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认导出文件名模板 的本地化字符串。
        /// </summary>
        public static string DefaultExportFileNameTemplate {
            get {
                return ResourceManager.GetString("DefaultExportFileNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认导出格式 的本地化字符串。
        /// </summary>
        public static string DefaultExportFormat {
            get {
                return ResourceManager.GetString("DefaultExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认固定宽度模式 的本地化字符串。
        /// </summary>
        public static string DefaultFixedWidth {
            get {
                return ResourceManager.GetString("DefaultFixedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认字体大小 的本地化字符串。
        /// </summary>
        public static string DefaultFontSize {
            get {
                return ResourceManager.GetString("DefaultFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认水平偏移 的本地化字符串。
        /// </summary>
        public static string DefaultHorizontalOffset {
            get {
                return ResourceManager.GetString("DefaultHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认水平扫描 的本地化字符串。
        /// </summary>
        public static string DefaultHorizontalScan {
            get {
                return ResourceManager.GetString("DefaultHorizontalScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认从左到右位序 的本地化字符串。
        /// </summary>
        public static string DefaultLeftToRight {
            get {
                return ResourceManager.GetString("DefaultLeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认像素高度 的本地化字符串。
        /// </summary>
        public static string DefaultPixelHeight {
            get {
                return ResourceManager.GetString("DefaultPixelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认像素宽度 的本地化字符串。
        /// </summary>
        public static string DefaultPixelWidth {
            get {
                return ResourceManager.GetString("DefaultPixelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认预览缩放 的本地化字符串。
        /// </summary>
        public static string DefaultPreviewZoom {
            get {
                return ResourceManager.GetString("DefaultPreviewZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认垂直偏移 的本地化字符串。
        /// </summary>
        public static string DefaultVerticalOffset {
            get {
                return ResourceManager.GetString("DefaultVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据最大高度 {0} 确定 的本地化字符串。
        /// </summary>
        public static string DeterminedByMaxHeight {
            get {
                return ResourceManager.GetString("DeterminedByMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据最大宽度 {0} 确定 的本地化字符串。
        /// </summary>
        public static string DeterminedByMaxWidth {
            get {
                return ResourceManager.GetString("DeterminedByMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接使用 CHAR_BITS[index] 访问第index个字符的点阵数据 的本地化字符串。
        /// </summary>
        public static string DirectCharAccess {
            get {
                return ResourceManager.GetString("DirectCharAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在: {0} 的本地化字符串。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已移除重复字符 的本地化字符串。
        /// </summary>
        public static string DuplicatesRemoved {
            get {
                return ResourceManager.GetString("DuplicatesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8位 (256灰度) 的本地化字符串。
        /// </summary>
        public static string EightBit256Gray {
            get {
                return ResourceManager.GetString("EightBit256Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8位 的本地化字符串。
        /// </summary>
        public static string EightBitText {
            get {
                return ResourceManager.GetString("EightBitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从资源文件名中提取的文化代码为空: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorExtractedCultureCodeIsEmpty {
            get {
                return ResourceManager.GetString("ErrorExtractedCultureCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源文件名格式无效，未找到Languages部分: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidResourceNameFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidResourceNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到任何语言资源文件。请确保项目中包含Languages.resx等资源文件。 的本地化字符串。
        /// </summary>
        public static string ErrorNoLanguageResourcesFound {
            get {
                return ResourceManager.GetString("ErrorNoLanguageResourcesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析任何有效的语言资源文件。 的本地化字符串。
        /// </summary>
        public static string ErrorNoValidLanguageResourcesParsed {
            get {
                return ResourceManager.GetString("ErrorNoValidLanguageResourcesParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源文件名不能为空 的本地化字符串。
        /// </summary>
        public static string ErrorResourceNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorResourceNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出设置... 的本地化字符串。
        /// </summary>
        public static string ExportSettings {
            get {
                return ResourceManager.GetString("ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出设置文件 的本地化字符串。
        /// </summary>
        public static string ExportSettingsFile {
            get {
                return ResourceManager.GetString("ExportSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string ExportTab {
            get {
                return ResourceManager.GetString("ExportTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取点阵数据 的本地化字符串。
        /// </summary>
        public static string ExtractBitmapData {
            get {
                return ResourceManager.GetString("ExtractBitmapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速滚动间隔(ms) 的本地化字符串。
        /// </summary>
        public static string FastScrollInterval {
            get {
                return ResourceManager.GetString("FastScrollInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式 的本地化字符串。
        /// </summary>
        public static string FileFormatLabel {
            get {
                return ResourceManager.GetString("FileFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前文件由FontMaker生成 的本地化字符串。
        /// </summary>
        public static string FileGeneratedBy {
            get {
                return ResourceManager.GetString("FileGeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在: {0} 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一个字符 的本地化字符串。
        /// </summary>
        public static string FirstChar {
            get {
                return ResourceManager.GetString("FirstChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个字符占用固定字节数，无需额外的宽高信息 的本地化字符串。
        /// </summary>
        public static string FixedWidthCharAccess {
            get {
                return ResourceManager.GetString("FixedWidthCharAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定宽度数据结构说明: 的本地化字符串。
        /// </summary>
        public static string FixedWidthDataStructure {
            get {
                return ResourceManager.GetString("FixedWidthDataStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定宽度：直接返回字符数据 的本地化字符串。
        /// </summary>
        public static string FixedWidthDirectAccess {
            get {
                return ResourceManager.GetString("FixedWidthDirectAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定宽度 的本地化字符串。
        /// </summary>
        public static string FixedWidthLabel {
            get {
                return ResourceManager.GetString("FixedWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹选择|*.folder 的本地化字符串。
        /// </summary>
        public static string FolderSelectionFilter {
            get {
                return ResourceManager.GetString("FolderSelectionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体： 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每像素位数: 1=黑白, 2=4级灰度, 4=16级灰度, 8=256级灰度 的本地化字符串。
        /// </summary>
        public static string FontBPP {
            get {
                return ResourceManager.GetString("FontBPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符总数 的本地化字符串。
        /// </summary>
        public static string FontCharCount {
            get {
                return ResourceManager.GetString("FontCharCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体文件 (*.ttf;*.otf)|*.ttf;*.otf|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string FontFileFilter {
            get {
                return ResourceManager.GetString("FontFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符高度(像素) 的本地化字符串。
        /// </summary>
        public static string FontHeight {
            get {
                return ResourceManager.GetString("FontHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字库已成功生成 的本地化字符串。
        /// </summary>
        public static string FontLibGenerated {
            get {
                return ResourceManager.GetString("FontLibGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每行字节数(向上取整) 的本地化字符串。
        /// </summary>
        public static string FontPitch {
            get {
                return ResourceManager.GetString("FontPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体渲染器不能为空 的本地化字符串。
        /// </summary>
        public static string FontRendererCannotBeNull {
            get {
                return ResourceManager.GetString("FontRendererCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体渲染 的本地化字符串。
        /// </summary>
        public static string FontRenderingTab {
            get {
                return ResourceManager.GetString("FontRenderingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体设置 的本地化字符串。
        /// </summary>
        public static string FontSetting {
            get {
                return ResourceManager.GetString("FontSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号： 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        public static string FontSizePixels {
            get {
                return ResourceManager.GetString("FontSizePixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧缩 的本地化字符串。
        /// </summary>
        public static string FontStretchCondensed {
            get {
                return ResourceManager.GetString("FontStretchCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        public static string FontStretchExpanded {
            get {
                return ResourceManager.GetString("FontStretchExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特紧缩 的本地化字符串。
        /// </summary>
        public static string FontStretchExtraCondensed {
            get {
                return ResourceManager.GetString("FontStretchExtraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特扩展 的本地化字符串。
        /// </summary>
        public static string FontStretchExtraExpanded {
            get {
                return ResourceManager.GetString("FontStretchExtraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半紧缩 的本地化字符串。
        /// </summary>
        public static string FontStretchSemiCondensed {
            get {
                return ResourceManager.GetString("FontStretchSemiCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半扩展 的本地化字符串。
        /// </summary>
        public static string FontStretchSemiExpanded {
            get {
                return ResourceManager.GetString("FontStretchSemiExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超紧缩 的本地化字符串。
        /// </summary>
        public static string FontStretchUltraCondensed {
            get {
                return ResourceManager.GetString("FontStretchUltraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超扩展 的本地化字符串。
        /// </summary>
        public static string FontStretchUltraExpanded {
            get {
                return ResourceManager.GetString("FontStretchUltraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        public static string FontStyleItalic {
            get {
                return ResourceManager.GetString("FontStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倾斜体 的本地化字符串。
        /// </summary>
        public static string FontStyleOblique {
            get {
                return ResourceManager.GetString("FontStyleOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string FontStyleRegular {
            get {
                return ResourceManager.GetString("FontStyleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体类型: 1=等宽字体, 0=变宽字体 的本地化字符串。
        /// </summary>
        public static string FontTypeMonospace {
            get {
                return ResourceManager.GetString("FontTypeMonospace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体类型: True=等宽字体, False=变宽字体 的本地化字符串。
        /// </summary>
        public static string FontTypeMonospacePy {
            get {
                return ResourceManager.GetString("FontTypeMonospacePy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极粗 的本地化字符串。
        /// </summary>
        public static string FontWeightBlack {
            get {
                return ResourceManager.GetString("FontWeightBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗体 的本地化字符串。
        /// </summary>
        public static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特粗 的本地化字符串。
        /// </summary>
        public static string FontWeightExtraBold {
            get {
                return ResourceManager.GetString("FontWeightExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半特细 的本地化字符串。
        /// </summary>
        public static string FontWeightExtraLight {
            get {
                return ResourceManager.GetString("FontWeightExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 细体 的本地化字符串。
        /// </summary>
        public static string FontWeightLight {
            get {
                return ResourceManager.GetString("FontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中等 的本地化字符串。
        /// </summary>
        public static string FontWeightMedium {
            get {
                return ResourceManager.GetString("FontWeightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半粗 的本地化字符串。
        /// </summary>
        public static string FontWeightSemiBold {
            get {
                return ResourceManager.GetString("FontWeightSemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超细 的本地化字符串。
        /// </summary>
        public static string FontWeightSemiLight {
            get {
                return ResourceManager.GetString("FontWeightSemiLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极细 的本地化字符串。
        /// </summary>
        public static string FontWeightThin {
            get {
                return ResourceManager.GetString("FontWeightThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特细 的本地化字符串。
        /// </summary>
        public static string FontWeightUltraLight {
            get {
                return ResourceManager.GetString("FontWeightUltraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符宽度(像素) 的本地化字符串。
        /// </summary>
        public static string FontWidth {
            get {
                return ResourceManager.GetString("FontWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4位 (16灰度) 的本地化字符串。
        /// </summary>
        public static string FourBit16Gray {
            get {
                return ResourceManager.GetString("FourBit16Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4位 的本地化字符串。
        /// </summary>
        public static string FourBitText {
            get {
                return ResourceManager.GetString("FourBitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成于 的本地化字符串。
        /// </summary>
        public static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成字库 的本地化字符串。
        /// </summary>
        public static string GenerateFontLibrary {
            get {
                return ResourceManager.GetString("GenerateFontLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据字符直接获取数据 的本地化字符串。
        /// </summary>
        public static string GetCharDataByChar {
            get {
                return ResourceManager.GetString("GetCharDataByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据索引获取字符数据 的本地化字符串。
        /// </summary>
        public static string GetCharDataByIndex {
            get {
                return ResourceManager.GetString("GetCharDataByIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据字符获取索引 的本地化字符串。
        /// </summary>
        public static string GetCharIndexByChar {
            get {
                return ResourceManager.GetString("GetCharIndexByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据字符获取字符信息 的本地化字符串。
        /// </summary>
        public static string GetCharInfoByChar {
            get {
                return ResourceManager.GetString("GetCharInfoByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从字符表中读取第index个字符信息 的本地化字符串。
        /// </summary>
        public static string GetCharInfoFromTable {
            get {
                return ResourceManager.GetString("GetCharInfoFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰度级别 的本地化字符串。
        /// </summary>
        public static string GrayLevelLabel {
            get {
                return ResourceManager.GetString("GrayLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度字节数 的本地化字符串。
        /// </summary>
        public static string HeightBytesCount {
            get {
                return ResourceManager.GetString("HeightBytesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平偏移 的本地化字符串。
        /// </summary>
        public static string HorizontalOffset {
            get {
                return ResourceManager.GetString("HorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平扫描 的本地化字符串。
        /// </summary>
        public static string HorizontalScan {
            get {
                return ResourceManager.GetString("HorizontalScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入字符集失败 的本地化字符串。
        /// </summary>
        public static string ImportCharSetFail {
            get {
                return ResourceManager.GetString("ImportCharSetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入字符集成功 的本地化字符串。
        /// </summary>
        public static string ImportCharSetSuccess {
            get {
                return ResourceManager.GetString("ImportCharSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入 {0} 个字符集 的本地化字符串。
        /// </summary>
        public static string ImportedCharSetMultiple {
            get {
                return ResourceManager.GetString("ImportedCharSetMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导入字符集: {0} 的本地化字符串。
        /// </summary>
        public static string ImportedCharSetSingle {
            get {
                return ResourceManager.GetString("ImportedCharSetSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入 {0} 个字体 的本地化字符串。
        /// </summary>
        public static string ImportedFontMultiple {
            get {
                return ResourceManager.GetString("ImportedFontMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导入字体: {0} 的本地化字符串。
        /// </summary>
        public static string ImportedFontSingle {
            get {
                return ResourceManager.GetString("ImportedFontSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下文件导入失败:\n{0} 的本地化字符串。
        /// </summary>
        public static string ImportFailedFilesList {
            get {
                return ResourceManager.GetString("ImportFailedFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入字体成功 的本地化字符串。
        /// </summary>
        public static string importFontSuccess {
            get {
                return ResourceManager.GetString("importFontSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据字符直接获取字符数据 的本地化字符串。
        /// </summary>
        public static string IndexAccessByChar {
            get {
                return ResourceManager.GetString("IndexAccessByChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据索引获取字符数据 的本地化字符串。
        /// </summary>
        public static string IndexAccessByIndex {
            get {
                return ResourceManager.GetString("IndexAccessByIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引访问说明: 的本地化字符串。
        /// </summary>
        public static string IndexAccessDescription {
            get {
                return ResourceManager.GetString("IndexAccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入要预览的文本... 的本地化字符串。
        /// </summary>
        public static string InputPreviewText {
            get {
                return ResourceManager.GetString("InputPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面 的本地化字符串。
        /// </summary>
        public static string InterfaceTab {
            get {
                return ResourceManager.GetString("InterfaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部辅助方法：根据索引获取原始字符数据 的本地化字符串。
        /// </summary>
        public static string InternalHelperGetRawCharData {
            get {
                return ResourceManager.GetString("InternalHelperGetRawCharData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的字符集文件或已存在同名字符集 的本地化字符串。
        /// </summary>
        public static string InvalidCharSetOrExists {
            get {
                return ResourceManager.GetString("InvalidCharSetOrExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的字体文件 的本地化字符串。
        /// </summary>
        public static string InvalidFontFile {
            get {
                return ResourceManager.GetString("InvalidFontFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效索引 的本地化字符串。
        /// </summary>
        public static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本文件包含 {0} 个字符，分割到多个内部类中 的本地化字符串。
        /// </summary>
        public static string JavaFileContainsChars {
            get {
                return ResourceManager.GetString("JavaFileContainsChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主类位于文件末尾 的本地化字符串。
        /// </summary>
        public static string JavaMainClassLocation {
            get {
                return ResourceManager.GetString("JavaMainClassLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主类名称 的本地化字符串。
        /// </summary>
        public static string JavaMainClassName {
            get {
                return ResourceManager.GetString("JavaMainClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java源文件 (*.java)|*.java 的本地化字符串。
        /// </summary>
        public static string JavaSourceFileFilter {
            get {
                return ResourceManager.GetString("JavaSourceFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON配置文件 (*.json)|*.json|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string JSONConfigFilter {
            get {
                return ResourceManager.GetString("JSONConfigFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一个字符 的本地化字符串。
        /// </summary>
        public static string LastChar {
            get {
                return ResourceManager.GetString("LastChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留空使用上次导出位置 的本地化字符串。
        /// </summary>
        public static string LeaveEmptyUseLastLocation {
            get {
                return ResourceManager.GetString("LeaveEmptyUseLastLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从左到右 的本地化字符串。
        /// </summary>
        public static string LeftToRightLabel {
            get {
                return ResourceManager.GetString("LeftToRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度/高度字节按小端序存储 (低字节在前) 的本地化字符串。
        /// </summary>
        public static string LittleEndianStorage {
            get {
                return ResourceManager.GetString("LittleEndianStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载字体变体失败: {0} 的本地化字符串。
        /// </summary>
        public static string LoadFontVariantError {
            get {
                return ResourceManager.GetString("LoadFontVariantError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置... 的本地化字符串。
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置文件 的本地化字符串。
        /// </summary>
        public static string LoadSettingsFile {
            get {
                return ResourceManager.GetString("LoadSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长按阈值(ms) 的本地化字符串。
        /// </summary>
        public static string LongPressThreshold {
            get {
                return ResourceManager.GetString("LongPressThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大缩放倍数 的本地化字符串。
        /// </summary>
        public static string MaxZoomScale {
            get {
                return ResourceManager.GetString("MaxZoomScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小缩放倍数 的本地化字符串。
        /// </summary>
        public static string MinZoomScale {
            get {
                return ResourceManager.GetString("MinZoomScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航： 的本地化字符串。
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择字体和字符集 的本地化字符串。
        /// </summary>
        public static string NeedSelectFontCharset {
            get {
                return ResourceManager.GetString("NeedSelectFontCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的设置已应用到界面，语言变更需要重启后生效 的本地化字符串。
        /// </summary>
        public static string NewSettingUpdate2UI {
            get {
                return ResourceManager.GetString("NewSettingUpdate2UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个字符 的本地化字符串。
        /// </summary>
        public static string NextChar {
            get {
                return ResourceManager.GetString("NextChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有成功导入任何字符集文件 的本地化字符串。
        /// </summary>
        public static string NoCharSetImported {
            get {
                return ResourceManager.GetString("NoCharSetImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择导出格式 的本地化字符串。
        /// </summary>
        public static string NoExportFormatSelected {
            get {
                return ResourceManager.GetString("NoExportFormatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择有效输出文件 的本地化字符串。
        /// </summary>
        public static string NoValidOutputFile {
            get {
                return ResourceManager.GetString("NoValidOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1位 (黑白) 的本地化字符串。
        /// </summary>
        public static string OneBitBlackWhite {
            get {
                return ResourceManager.GetString("OneBitBlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1位 的本地化字符串。
        /// </summary>
        public static string OneBitText {
            get {
                return ResourceManager.GetString("OneBitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开设置窗口失败 的本地化字符串。
        /// </summary>
        public static string OpenSettingWinFail {
            get {
                return ResourceManager.GetString("OpenSettingWinFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出失败 的本地化字符串。
        /// </summary>
        public static string OutputFail {
            get {
                return ResourceManager.GetString("OutputFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成字库... 的本地化字符串。
        /// </summary>
        public static string OutputFontLibing {
            get {
                return ResourceManager.GetString("OutputFontLibing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出设置 的本地化字符串。
        /// </summary>
        public static string OutputSetting {
            get {
                return ResourceManager.GetString("OutputSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        public static string OutputSuccess {
            get {
                return ResourceManager.GetString("OutputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分字符集导入失败 的本地化字符串。
        /// </summary>
        public static string PartialCharSetImportFail {
            get {
                return ResourceManager.GetString("PartialCharSetImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分字体导入失败 的本地化字符串。
        /// </summary>
        public static string PartialFontImportFail {
            get {
                return ResourceManager.GetString("PartialFontImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点阵大小 的本地化字符串。
        /// </summary>
        public static string PointSize {
            get {
                return ResourceManager.GetString("PointSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览失败 的本地化字符串。
        /// </summary>
        public static string PreviewFail {
            get {
                return ResourceManager.GetString("PreviewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string PreviewTab {
            get {
                return ResourceManager.GetString("PreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览文本 的本地化字符串。
        /// </summary>
        public static string PreviewText {
            get {
                return ResourceManager.GetString("PreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个字符 的本地化字符串。
        /// </summary>
        public static string PreviousChar {
            get {
                return ResourceManager.GetString("PreviousChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python源文件 (*.py)|*.py 的本地化字符串。
        /// </summary>
        public static string PythonSourceFileFilter {
            get {
                return ResourceManager.GetString("PythonSourceFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷操作 的本地化字符串。
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取高度 (小端序) 的本地化字符串。
        /// </summary>
        public static string ReadHeightLittleEndian {
            get {
                return ResourceManager.GetString("ReadHeightLittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取宽度 (小端序) 的本地化字符串。
        /// </summary>
        public static string ReadWidthLittleEndian {
            get {
                return ResourceManager.GetString("ReadWidthLittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去重 的本地化字符串。
        /// </summary>
        public static string RemoveDuplicates {
            get {
                return ResourceManager.GetString("RemoveDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除重复的字符 的本地化字符串。
        /// </summary>
        public static string RemoveDuplicatesTooltip {
            get {
                return ResourceManager.GetString("RemoveDuplicatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除当前字体不支持的字符 的本地化字符串。
        /// </summary>
        public static string RemoveUnsupportedChars {
            get {
                return ResourceManager.GetString("RemoveUnsupportedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要恢复所有设置为默认值吗？这将覆盖当前的所有设置。 的本地化字符串。
        /// </summary>
        public static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string ResetTooltip {
            get {
                return ResourceManager.GetString("ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认 的本地化字符串。
        /// </summary>
        public static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从右到左 的本地化字符串。
        /// </summary>
        public static string RightToLeftLabel {
            get {
                return ResourceManager.GetString("RightToLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描方式 的本地化字符串。
        /// </summary>
        public static string ScanMethod {
            get {
                return ResourceManager.GetString("ScanMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平扫描 的本地化字符串。
        /// </summary>
        public static string ScanMethodHorizontal {
            get {
                return ResourceManager.GetString("ScanMethodHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直扫描 的本地化字符串。
        /// </summary>
        public static string ScanMethodVertical {
            get {
                return ResourceManager.GetString("ScanMethodVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字符集文件 的本地化字符串。
        /// </summary>
        public static string SelectCharSetFile {
            get {
                return ResourceManager.GetString("SelectCharSetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择默认导出目录 的本地化字符串。
        /// </summary>
        public static string SelectDefaultExportDir {
            get {
                return ResourceManager.GetString("SelectDefaultExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字体文件 的本地化字符串。
        /// </summary>
        public static string SelectFontFile {
            get {
                return ResourceManager.GetString("SelectFontFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择此文件夹 的本地化字符串。
        /// </summary>
        public static string SelectThisFolder {
            get {
                return ResourceManager.GetString("SelectThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已更新 的本地化字符串。
        /// </summary>
        public static string SetingUpdated {
            get {
                return ResourceManager.GetString("SetingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出设置文件失败：{0} 的本地化字符串。
        /// </summary>
        public static string SettingsExportFail {
            get {
                return ResourceManager.GetString("SettingsExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件导出成功！ 的本地化字符串。
        /// </summary>
        public static string SettingsExportSuccess {
            get {
                return ResourceManager.GetString("SettingsExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件格式不正确或不完整！ 的本地化字符串。
        /// </summary>
        public static string SettingsFileFormatError {
            get {
                return ResourceManager.GetString("SettingsFileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置文件失败！ 的本地化字符串。
        /// </summary>
        public static string SettingsLoadFail {
            get {
                return ResourceManager.GetString("SettingsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件加载成功！ 的本地化字符串。
        /// </summary>
        public static string SettingsLoadSuccess {
            get {
                return ResourceManager.GetString("SettingsLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置失败：{0} 的本地化字符串。
        /// </summary>
        public static string SettingsSaveFail {
            get {
                return ResourceManager.GetString("SettingsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string SortCharacters {
            get {
                return ResourceManager.GetString("SortCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 Unicode 值排序字符 的本地化字符串。
        /// </summary>
        public static string SortCharactersTooltip {
            get {
                return ResourceManager.GetString("SortCharactersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准字符集 的本地化字符串。
        /// </summary>
        public static string StandardCharSet {
            get {
                return ResourceManager.GetString("StandardCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持变量：{FontName} {CharsetName} {FontSize} {Width} {Height} {BPP} {DateTime} 等 的本地化字符串。
        /// </summary>
        public static string SupportedVariables {
            get {
                return ResourceManager.GetString("SupportedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本预览行间距 的本地化字符串。
        /// </summary>
        public static string TextPreviewLineSpacing {
            get {
                return ResourceManager.GetString("TextPreviewLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本预览 的本地化字符串。
        /// </summary>
        public static string TextPreviewTitle {
            get {
                return ResourceManager.GetString("TextPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2位 (4灰度) 的本地化字符串。
        /// </summary>
        public static string TwoBit4Gray {
            get {
                return ResourceManager.GetString("TwoBit4Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2位 的本地化字符串。
        /// </summary>
        public static string TwoBitText {
            get {
                return ResourceManager.GetString("TwoBitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择字体，无法进行渲染 的本地化字符串。
        /// </summary>
        public static string UnselectedFontError {
            get {
                return ResourceManager.GetString("UnselectedFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的导出格式: {0} 的本地化字符串。
        /// </summary>
        public static string UnsupportedExportFormat {
            get {
                return ResourceManager.GetString("UnsupportedExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的语言代码: {0} 的本地化字符串。
        /// </summary>
        public static string UnsupportedLanguageCode {
            get {
                return ResourceManager.GetString("UnsupportedLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用get_char_info()获取解析后的字符信息 的本地化字符串。
        /// </summary>
        public static string UseCharInfoForParsing {
            get {
                return ResourceManager.GetString("UseCharInfoForParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户自定义 的本地化字符串。
        /// </summary>
        public static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证错误 的本地化字符串。
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度字符信息类 的本地化字符串。
        /// </summary>
        public static string VariableWidthCharInfoClass {
            get {
                return ResourceManager.GetString("VariableWidthCharInfoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度字符读取辅助函数 的本地化字符串。
        /// </summary>
        public static string VariableWidthCharReadHelper {
            get {
                return ResourceManager.GetString("VariableWidthCharReadHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度字符读取辅助函数 的本地化字符串。
        /// </summary>
        public static string VariableWidthCharReadHelper_Duplicate_1_ {
            get {
                return ResourceManager.GetString("VariableWidthCharReadHelper_Duplicate[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度数据结构说明: 的本地化字符串。
        /// </summary>
        public static string VariableWidthDataStructure {
            get {
                return ResourceManager.GetString("VariableWidthDataStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度字体专用：根据字符获取解析后的字符信息 的本地化字符串。
        /// </summary>
        public static string VariableWidthExclusiveAccess {
            get {
                return ResourceManager.GetString("VariableWidthExclusiveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度 的本地化字符串。
        /// </summary>
        public static string VariableWidthLabel {
            get {
                return ResourceManager.GetString("VariableWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度：返回原始数据块（包含宽高信息） 的本地化字符串。
        /// </summary>
        public static string VariableWidthRawAccess {
            get {
                return ResourceManager.GetString("VariableWidthRawAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直偏移 的本地化字符串。
        /// </summary>
        public static string VerticalOffset {
            get {
                return ResourceManager.GetString("VerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直扫描 的本地化字符串。
        /// </summary>
        public static string VerticalScan {
            get {
                return ResourceManager.GetString("VerticalScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览缩放 的本地化字符串。
        /// </summary>
        public static string ViewResize {
            get {
                return ResourceManager.GetString("ViewResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度字节数 的本地化字符串。
        /// </summary>
        public static string WidthBytesCount {
            get {
                return ResourceManager.GetString("WidthBytesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度模式 的本地化字符串。
        /// </summary>
        public static string WidthMode {
            get {
                return ResourceManager.GetString("WidthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定宽度 的本地化字符串。
        /// </summary>
        public static string WidthModeFixed {
            get {
                return ResourceManager.GetString("WidthModeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变宽度 的本地化字符串。
        /// </summary>
        public static string WidthModeVariable {
            get {
                return ResourceManager.GetString("WidthModeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放: 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string ZoomInTooltip {
            get {
                return ResourceManager.GetString("ZoomInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string ZoomOutTooltip {
            get {
                return ResourceManager.GetString("ZoomOutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放步长 的本地化字符串。
        /// </summary>
        public static string ZoomStep {
            get {
                return ResourceManager.GetString("ZoomStep", resourceCulture);
            }
        }
    }
}
